name: fluentui_icons
description: Microsoft Fluent UI Icons based on the official repo
version: 0.0.1
author: Alberto Bonacina <bonacina.alberto@gmail.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family:  FluentSystemIcons
      fonts:
        - asset: fonts/FluentSystemIcons.ttf
